### ISSUE TITLE
Error message: "Error: [] lengths of of cells and values do not match" 

### ISSUE THREAD

**Issue by DavidAClarke** [bafuentes/rassta#1]
I am having an issue running the `som_pam` function where I a get the `Error: [] lengths of of cells and values do not match` message. 
Upon examining the code for `som_pam` and running the code line by line I found out that the issue occurs at `r.som[idx] <- terr.som$SOM$unit.classif`. Essentially, for some reason the number of values don't match, i.e. `length(values(r.som)) == length(terr.som$SOM$unit.classif)` is `FALSE`. 

Can you think of a reason why this may be occurring? Are there parameters I should alter in the `som_gap` function as I assume something is happening here where the number of cells in the input rasters is being altered when producing the classification units.

**Comment by bafuentes** [comment]
It is hard to trace back the source of your error without a reproducible example. Nevertheless, could you please tell me if you are using a single layer SpatRaster object in the function `som_pam()` (argument `ref.rast`), that matches perfectly with the layers from the SpatRaster object that you used as input in the function `som_gap()` (argument `var.rast`)? 

A perfect match between `ref.rast` and `var.rast` only means that they must have the same cell size, number of rows, number of columns, and index of valid cells (as mentioned in the `Description` field of `som_pam()`). Normally, you would use one of the layers from `var.rast` as the reference layer in `ref.rast` to prevent any mismatch (e.g., `Error: [] lengths of of cells and values do not match`).

**Comment by DavidAClarke** [comment]
I used a multi-layer SpatRaster object for the `som_gap` function. I have been following your example [here](https://bafuentes.github.io/rassta/articles/classunits.html). As such, I did use one of my `var.rast` layers to create the `ref.rast` but the error still occurs.

Is there are a convenient way for me to send you my raster layers? In the meantime this is what my code looks like:

`var <- c("BH_REMA_8M.tif", "BH_aspect.tif", "BH_slope.tif", "BH_rough.tif",
         "BH_TRI.tif", "BH_TPI.tif", "BH_flow.tif")`
`varpath <- file.path("Data", "REMA")`
`vardir <- paste(varpath, var, sep = "/")`
`terr.var <- rast(vardir)`
`terr.varscale <- terra::scale(terr.var)`
`terr.varscale <- aggregate(terr.varscale, fact = 3) #8 to 24`
`terr.som <- som_gap(terr.varscale, xdim = 9, ydim = 9, K.max = 9)`

`rastref <- aggregate(terr.var[[1]], fact = 3)`
`terr.sompam <- som_pam(ref.rast = rastref, kohsom = terr.som$SOM,
                       k = terr.som$Kopt)`

**Comment by bafuentes** [comment]
Thanks. You can send me your raster layers by email (which appears on my profile). I will try your code example as soon as I get them.

**Comment by bafuentes** [comment]
In the meantime, could you please try:
 ` terr.sompam <- som_pam(ref.rast = terr.varscale[[1]], kohsom = terr.som$SOM, k = terr.som$Kopt)`

**Comment by DavidAClarke** [comment]
Using `terr.varscale[[1]]` also did not work.

**Comment by bafuentes** [comment]
I checked your raster layers and it seems that some of them have a different number of valid/`NA` cells. This represents an input data issue because the index of valid cells in the reference layer `ref.rast` will not match that index from some of the raster layers in `var.rast`.

Given your data, something you can do is to try each of the layers in `var.rast` as the input for `ref.rast`. There must be one layer whose number of valid cells matches the number of elements in `terr.som$SOM$unit.classif`.

Please let me know how this goes.

**Comment by DavidAClarke** [comment]
Using a different `var.rast` for the `ref.rast` did indeed work. I guess there may just need to be some trial and error with using different `var.rast` layers if one gets the original error message upon running `som_pam` the first time.

I wonder if running something like `ENMTools::check.env()` on the raster stack (which propagates NA's so that layers are the same) before running `som_gap`  would help? I may play with this.

Thanks very much for your assistance!
